services:
  bot:
    image: ${DOCKERHUB_USERNAME}/social-media-bot:latest
    environment:
        - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
        - TELEGRAM_GROUP_ID=${TELEGRAM_GROUP_ID}
        - X_API_KEY=${X_API_KEY}
        - X_API_SECRET=${X_API_SECRET}
        - X_ACCESS_TOKEN=${X_ACCESS_TOKEN}
        - X_ACCESS_TOKEN_SECRET=${X_ACCESS_TOKEN_SECRET}
        - ALLOWED_USER_ID=${ALLOWED_USER_ID}
        - MAX_MEDIA_FILES=10
        - MAX_TEXT_LENGTH=2000
    depends_on:
      - telegram-bot-api
    networks:
      - bot-network

  telegram-bot-api:
    image: aiogram/telegram-bot-api:latest
    environment:
      - TELEGRAM_API_ID=${TELEGRAM_API_ID}
      - TELEGRAM_API_HASH=${TELEGRAM_API_HASH}
      - TELEGRAM_LOCAL=1
    volumes:
      - telegram-bot-api-data:/var/lib/telegram-bot-api
    networks:
      - bot-network

networks:
  bot-network:
    driver: bridge

volumes:
  telegram-bot-api-data:
