name: Build and Deploy Docker Image

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/social-media-bot:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Deploy to server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: 22
          script: |
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/social-media-bot:latest

            docker stop social-media-bot || true
            docker rm social-media-bot || true

            docker run -d --name social-media-bot \
              -e TELEGRAM_BOT_TOKEN=${{ secrets.TELEGRAM_BOT_TOKEN }} \
              -e TELEGRAM_GROUP_ID=${{ secrets.TELEGRAM_GROUP_ID }} \
              -e X_API_KEY=${{ secrets.X_API_KEY }} \
              -e X_API_SECRET=${{ secrets.X_API_SECRET }} \
              -e X_ACCESS_TOKEN=${{ secrets.X_ACCESS_TOKEN }} \
              -e X_ACCESS_TOKEN_SECRET=${{ secrets.X_ACCESS_TOKEN_SECRET }} \
              -e ALLOWED_USER_ID=${{ secrets.ALLOWED_USER_ID }} \
              -e MAX_MEDIA_FILES=10 \
              -e MAX_TEXT_LENGTH=2000 \
              ${{ secrets.DOCKERHUB_USERNAME }}/social-media-bot:latest

            docker image prune -f